spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/local
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-authentication-method: client_secret_post
            client-id: e5894ef41cfc732054cfa4324c4037c8
            client-secret: l5Jx5R87pS461hiTvz3OqoDhQa6fgZ0V
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname,profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  mail:
    host: spring.mail.host=smtp.gmail.com
    port: 587
    username: lch6648850@gmail.com
    password: 123456
    properties:
      smtp:
        starttls:
          enable: true
        auth: true
kakao:
  logout-redirect-uri: http://localhost:8080
  logout-url: https://kauth.kakao.com/oauth/logout